version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: quantumpay_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: quantum_admin
      POSTGRES_PASSWORD: quantum_secret
      POSTGRES_DB: quantumpay_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
